security:
  # Password hashers
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # User providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UserAuthenticator
      logout:
        path: app_logout
        # target: app_any_route
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /

  # Role hierarchy
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  # Access control
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/perfil, roles: ROLE_USER }
    - { path: ^/uploads/headers, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/uploads/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/pagina/all, roles: ROLE_ADMIN }
    - { path: ^/pagina/new, roles: ROLE_ADMIN }
    - { path: ^/pagina/delete, roles: ROLE_ADMIN }
    - { path: ^/pagina/edit, roles: ROLE_ADMIN }
    - { path: ^/ayuda/, roles: ROLE_ADMIN }
    - { path: ^/carpeta/, roles: ROLE_ADMIN }
    - { path: ^/imagen/, roles: ROLE_ADMIN }
    - { path: ^/menu/, roles: ROLE_ADMIN }
    - { path: ^/perfil/, roles: ROLE_ADMIN }
    - { path: ^/sitio/, roles: ROLE_ADMIN }
    - { path: ^/usuario/, roles: ROLE_ADMIN }
