controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

pagina_show:
  path: /{ruta}
  controller: App\Controller\PaginaController::show
  requirements:
    ruta: ".+"

pagina_inicio:
  path: /
  controller: App\Controller\PaginaController::inicio
