controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

pagina_inicio:
  path: /
  controller: App\Controller\PaginaController::inicio

contacto:
  path: /contacto
  controller: App\Controller\PaginaController::contacto

ayuda:
  path: /ayuda
  controller: App\Controller\AyudaController::index

pagina_show:
  path: /{ruta}
  controller: App\Controller\PaginaController::show
  requirements:
    ruta: ".+"
